version: '3'
services:
  genshin-app:
    container_name: genshin-app
    build:
      context: .
      dockerfile: Dockerfile
    command: nodemon --legacy-watch index.js
    ports:
      - 8400:8400
    depends_on:
      - database
    volumes:
      - ./source:/app/source
  database:
    image: postgres:13
    container_name: database
    ports:
      - 2345:5432
    env_file:
      - .env
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
